### ISSUE TITLE
Left / right clicking volume / hardware / network tray icons does not work

### ISSUE THREAD

**Issue by BlohoJo** [AEAEAEAE4343/SimpleClassicThemeTaskbar#18]
Right or left clicking any of the built in Windows system tray icons for Volume, Safely Remove Hardware, and Networking returns this error:

![error](https://user-images.githubusercontent.com/8242464/112370895-56037080-8cb4-11eb-9893-cff553195859.png)

 
There are no Windows Events logs, but there are logs created in the SCTT folder:

 
outside-taskbar-crash2021-24-3--15-02-41:
```
Win32Exception
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName)
   at SimpleClassicThemeTaskbar.UIElements.SystemTray.SystemTrayIcon.<.ctor>b__17_2(Object sender, MouseEventArgs e)
   at System.Windows.Forms.Control.OnMouseClick(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
The system cannot find the file specified.
System.Diagnostics.Process
```

 
outside-taskbar-crash2021-24-3--15-02-45:
```
Win32Exception
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName)
   at SimpleClassicThemeTaskbar.UIElements.SystemTray.SystemTrayIcon.<.ctor>b__17_2(Object sender, MouseEventArgs e)
   at System.Windows.Forms.Control.OnMouseClick(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
The system cannot find the file specified.
System.Diagnostics.Process
```

 
outside-taskbar-crash2021-24-3--15-02-48:
```
Win32Exception
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName)
   at SimpleClassicThemeTaskbar.UIElements.SystemTray.SystemTrayIcon.<.ctor>b__17_2(Object sender, MouseEventArgs e)
   at System.Windows.Forms.Control.OnMouseClick(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
The system cannot find the file specified.
System.Diagnostics.Process
```

**Comment by AEAEAEAE4343** [comment]
The new tray implementation will fix this but it won't be available for a while since it's not stable at all.
