### ISSUE TITLE
"Unhandled Exception" dialog if more than 6 taskbar buttons

### ISSUE THREAD

**Issue by BlohoJo** [AEAEAEAE4343/SimpleClassicThemeTaskbar#19]
If I open multiple windows or programs, as soon as more than 6 task bar buttons appear on the task bar, I get this message:

![unhandled](https://user-images.githubusercontent.com/8242464/113045983-7d06ea00-916d-11eb-8cfa-950995786464.png)

I can click OK to close it.

None of the open programs close, none of the task bar buttons disappear or stop working, and SCTT continues to function.

But, the message above will pop up again within 3 - 10 seconds, and continue to do so, until I close enough programs or windows to get it to stop.

When the message is up, I cannot use the task bar. For example, if I click a task bar button to bring an open window to the foreground, it instead brings the above message to the foreground. Until I click OK on the message, the task bar is locked.

So obviously this makes it very difficult to work when there are more than 6 task bar buttons.

No Windows event log is generated.

A SCTT log event is generated every time the message appears. Here's the contents of one:

```
ArgumentException
   at System.Drawing.Graphics.GetHdc()
   at System.Drawing.Internal.WindowsGraphics.FromGraphics(Graphics g, ApplyGraphicsProperties properties)
   at System.Drawing.Icon.Draw(Graphics graphics, Rectangle targetRect)
   at System.Drawing.Icon.BmpFrame()
   at SimpleClassicThemeTaskbar.SingleTaskbarProgram.set_Icon(Icon value)
   at SimpleClassicThemeTaskbar.Taskbar.timerUpdateUI_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
Parameter is not valid.
System.Drawing.Common
```

Here's a zip of all of the logs generated so far:
[Taskbar_Exiting_Messages.zip](https://github.com/AEAEAEAE4343/SimpleClassicThemeTaskbar/files/6231736/Taskbar_Exiting_Messages.zip)

Here's my config info:

Windows 10 Pro x64 2004

![sctt_01](https://user-images.githubusercontent.com/8242464/113046118-a758a780-916d-11eb-9a4f-c24bb2c3a456.png)

![sctt_02](https://user-images.githubusercontent.com/8242464/113046145-ae7fb580-916d-11eb-96f5-858dee49754a.png)
![XP Classic (Bigger) (SCTT)](https://user-images.githubusercontent.com/8242464/113046181-bccdd180-916d-11eb-8e90-1b666c89871a.png)

![sctt_03](https://user-images.githubusercontent.com/8242464/113046187-c1928580-916d-11eb-9467-698f93db3042.png)

![sctt_04](https://user-images.githubusercontent.com/8242464/113046208-ca835700-916d-11eb-9966-7a8eda3c8c8a.png)

**Comment by AEAEAEAE4343** [comment]
I can't seem to reproduce this issue. Is it still present in the latest version? (Beta, not Development)

**Comment by BlohoJo** [comment]
Yes, as shown above... to double check, I just downloaded the latest beta zip and double checked the crc of the executable and they match what I'm using.

I'm running Windows 10 x64 Pro 2004 (20H1), along with [UltraUXThemePatcher](https://mhoefs.eu/software_uxtheme.php?lang=en) 4.0.0, and [Malvinas Classic Theme for Windows 10 version 1909](https://github.com/malvinas2/ClassicThemeForWindows10/tree/master/Theme%20For%20Win10%20November%202019%20Update%201909) (the highest Windows version available for the theme).

I'm wondering if there isn't a conflict with SCT/SCTT and the above theme.

Could you try installing / enabling the above theme? You need to have UltraUXThemePatcher installed.

(Never install UltraUXThemePatcher without setting the below registry key:)

```
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Power]
"HiberbootEnabled"=dword:00000000
```

**Comment by BlohoJo** [comment]
I just tried changing themes back to Windows 10 default, and it still happens.

I also get "Unhandled Exception Occurred" when right clicking any running application button on the taskbar. I can't remember if that's supposed to happen with the latest SCTT beta or not.

**Comment by BlohoJo** [comment]
Another thing I should mention, is that this is a VPS running on a hypervisor. So there's no GPU or Nvidia/AMD drivers installed.

**Comment by Craftplacer** [comment]
Maybe we should wait until we have a "SCTT 2.0" out, where we have rewritten/refactored the code.
