### ISSUE TITLE
SCT crashes on startup with file not being found

### ISSUE THREAD

**Issue by Craftplacer** [AEAEAEAE4343/SimpleClassicThemeTaskbar#21]
I tried the development build and it crashed immediately. (Clicking "enable" in SCT.)

It appears to be missing a file called `SimpleClassicThemeTaskbar.CodeBridge`

```
Faulting application name: SimpleClassicThemeTaskbar.exe, version: 0.0.7804.42771, time stamp: 0x60513887
Faulting module name: KERNELBASE.dll, version: 10.0.19041.572, time stamp: 0x1183946c
Exception code: 0xe0434352
Fault offset: 0x0000000000023e49
Faulting process id: 0xd98
Faulting application start time: 0x01d74920205c0c5f
Faulting application path: C:\SCT\Taskbar\SimpleClassicThemeTaskbar.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 6acac671-d915-4575-be43-b72a380ba969
Faulting package full name: 
Faulting package-relative application ID:
```

```
Application: SimpleClassicThemeTaskbar.exe
CoreCLR Version: 5.0.521.16609
.NET Version: 5.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException: Could not load file or assembly 'SimpleClassicThemeTaskbar.CodeBridge, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'SimpleClassicThemeTaskbar.CodeBridge, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
   at SimpleClassicThemeTaskbar.ApplicationEntryPoint.Main(String[] args)
```

_Originally posted by @BlohoJo in https://github.com/AEAEAEAE4343/SimpleClassicThemeTaskbar/issues/20#issuecomment-841570197_

**Comment by BlohoJo** [comment]
Still getting the error in latest development build.

Is it maybe my file structure? I have it set up as it was in the previous working version, with SCTT binaries in a folder called "Taskbar" under the SCT folder, which I have in C:\SCT:

```
C:\SCT>dir /a /s /ogn
 Volume in drive C has no label.
 Volume Serial Number is D0A4-4616

 Directory of C:\SCT

05/17/2021  01:56 AM    <DIR>          .
05/17/2021  01:56 AM    <DIR>          ..
05/17/2021  01:31 AM    <DIR>          Taskbar
03/01/2021  09:46 PM            54,784 deskn.cpl
12/01/2020  11:38 PM               725 DisableThemeScript.bat
03/13/2021  12:27 PM               722 EnableThemeScript.bat
02/08/2021  06:07 PM               788 EnableThemeScript.old
02/08/2021  05:31 PM        13,087,744 SCT.exe
               5 File(s)     13,144,763 bytes

 Directory of C:\SCT\Taskbar

05/17/2021  01:31 AM    <DIR>          .
05/17/2021  01:31 AM    <DIR>          ..
05/16/2021  08:25 PM    <DIR>          nl
05/16/2021  08:25 PM    <DIR>          nl-NL
05/16/2021  08:25 PM    <DIR>          ref
05/16/2021  08:25 PM            29,184 ManagedWifi.dll
05/16/2021  08:25 PM           350,720 SimpleClassicThemeTaskbar.CodeBridge.dll
05/16/2021  08:25 PM         1,658,880 SimpleClassicThemeTaskbar.CodeBridge.pdb
05/16/2021  08:25 PM             1,101 SimpleClassicThemeTaskbar.deps.json
05/16/2021  08:25 PM           795,136 SimpleClassicThemeTaskbar.dll
05/16/2021  08:25 PM               332 SimpleClassicThemeTaskbar.dll.config
05/16/2021  08:25 PM           382,976 SimpleClassicThemeTaskbar.exe
05/16/2021  08:25 PM            57,856 SimpleClassicThemeTaskbar.pdb
05/16/2021  08:25 PM               391 SimpleClassicThemeTaskbar.runtimeconfig.dev.json
05/16/2021  08:25 PM               154 SimpleClassicThemeTaskbar.runtimeconfig.json
              10 File(s)      3,276,730 bytes

 Directory of C:\SCT\Taskbar\nl

05/16/2021  08:25 PM    <DIR>          .
05/16/2021  08:25 PM    <DIR>          ..
05/16/2021  08:25 PM           148,992 SimpleClassicThemeTaskbar.resources.dll
               1 File(s)        148,992 bytes

 Directory of C:\SCT\Taskbar\nl-NL

05/16/2021  08:25 PM    <DIR>          .
05/16/2021  08:25 PM    <DIR>          ..
05/16/2021  08:25 PM           153,088 SimpleClassicThemeTaskbar.resources.dll
               1 File(s)        153,088 bytes

 Directory of C:\SCT\Taskbar\ref

05/16/2021  08:25 PM    <DIR>          .
05/16/2021  08:25 PM    <DIR>          ..
05/16/2021  08:25 PM           268,800 SimpleClassicThemeTaskbar.dll
               1 File(s)        268,800 bytes

     Total Files Listed:
              18 File(s)     16,992,373 bytes
              14 Dir(s)  3,583,866,093,568 bytes free
```

I tried running x64dbg. The results are below. Line 87 is interesting...

```
DLL Loaded: 000002044C590000 C:\SCT\binaries\SimpleClassicThemeTaskbar.dll
```
...since there is no such location. For testing, I renamed `C:\SCT\Taskbar\` to `C:\SCT\binaries\`, but it had no effect on the problem.

Here's the full x64dbg log, just in case it might be useful:

```
Initializing wait objects...
Initializing debugger...
Initializing debugger functions...
Setting JSON memory management functions...
Initializing Zydis...
Getting directory information...
Start file read thread...
Retrieving syscall indices...
Symbol Path: C:\Program Files\x64dbg\x64\symbols
Allocating message stack...
Initializing global script variables...
Registering debugger commands...
Registering GUI command handler...
Registering expression functions...
Registering format functions...
Registering Script DLL command handler...
Starting command loop...
Initialization successful!
Loading plugins...
Handling command line...
  "C:\Program Files\x64dbg\x64\x64dbg.exe" 
Syscall indices loaded!
Error codes database loaded!
Exception codes database loaded!
NTSTATUS codes database loaded!
Windows constant database loaded!
Reading notes file...
File read thread finished!
Debugging: C:\SCT\Taskbar\SimpleClassicThemeTaskbar.exe
Database file: C:\Program Files\x64dbg\x64\db\SimpleClassicThemeTaskbar.exe.dd64
Process Started: 00007FF7F2E90000 C:\SCT\Taskbar\SimpleClassicThemeTaskbar.exe
  "C:\SCT\Taskbar\SimpleClassicThemeTaskbar.exe"
  argv[0]: C:\SCT\Taskbar\SimpleClassicThemeTaskbar.exe
Breakpoint at 00007FF7F2E9FF70 (entry breakpoint) set!
DLL Loaded: 00007FFC3C650000 C:\Windows\System32\ntdll.dll
DLL Loaded: 00007FFC3B330000 C:\Windows\System32\kernel32.dll
DLL Loaded: 00007FFC39D90000 C:\Windows\System32\KernelBase.dll
DLL Loaded: 00007FFC3B7C0000 C:\Windows\System32\user32.dll
DLL Loaded: 00007FFC3A100000 C:\Windows\System32\win32u.dll
DLL Loaded: 00007FFC3B300000 C:\Windows\System32\gdi32.dll
DLL Loaded: 00007FFC3A210000 C:\Windows\System32\gdi32full.dll
DLL Loaded: 00007FFC3A060000 C:\Windows\System32\msvcp_win.dll
DLL Loaded: 00007FFC3A320000 C:\Windows\System32\ucrtbase.dll
Thread 1F64 created, Entry: ntdll.00007FFC3C6620E0
Thread 4E4 created, Entry: ntdll.00007FFC3C6620E0
DLL Loaded: 00007FFC3AAD0000 C:\Windows\System32\shell32.dll
Thread 14E4 created, Entry: ntdll.00007FFC3C6620E0
DLL Loaded: 00007FFC3B660000 C:\Windows\System32\advapi32.dll
DLL Loaded: 00007FFC3A9D0000 C:\Windows\System32\msvcrt.dll
DLL Loaded: 00007FFC3B480000 C:\Windows\System32\sechost.dll
DLL Loaded: 00007FFC3A8A0000 C:\Windows\System32\rpcrt4.dll
System breakpoint reached!
DLL Loaded: 00007FFC3A870000 C:\Windows\System32\imm32.dll
DLL Loaded: 0000000180000000 C:\Program Files\Prio\prio.dll
INT3 breakpoint "entry breakpoint" at <simpleclassicthemetaskbar.EntryPoint> (00007FF7F2E9FF70)!
DLL Loaded: 00007FFC01D70000 C:\Program Files\dotnet\host\fxr\5.0.5\hostfxr.dll
DLL Loaded: 00007FFC01CF0000 C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.5\hostpolicy.dll
Breakpoint at 00007FFC0191BBE0 (TLS Callback 1 (coreclr.dll)) set!
Breakpoint at 00007FFC0191C040 (TLS Callback 2 (coreclr.dll)) set!
DLL Loaded: 00007FFC017E0000 C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.5\coreclr.dll
DLL Loaded: 00007FFC3BF60000 C:\Windows\System32\ole32.dll
DLL Loaded: 00007FFC3BC00000 C:\Windows\System32\combase.dll
DLL Loaded: 00007FFC3B230000 C:\Windows\System32\oleaut32.dll
INT3 breakpoint "TLS Callback 1 (coreclr.dll)" at coreclr.00007FFC0191BBE0 (00007FFC0191BBE0)!
INT3 breakpoint "TLS Callback 2 (coreclr.dll)" at coreclr.00007FFC0191C040 (00007FFC0191C040)!
DLL Loaded: 00007FFC3A630000 C:\Windows\System32\bcryptprimitives.dll
Thread 1CDC created, Entry: coreclr.00007FFC018C4ED0
EXCEPTION_DEBUG_INFO:
           dwFirstChance: 1
           ExceptionCode: 04242420 (CLRDBG_NOTIFICATION_EXCEPTION_CODE)
          ExceptionFlags: 00000000
        ExceptionAddress: 00007FFC39DB3E49 kernelbase.00007FFC39DB3E49
        NumberParameters: 3
ExceptionInformation[00]: 0000000031415927
ExceptionInformation[01]: 00007FFC017E0000 coreclr.00007FFC017E0000
ExceptionInformation[02]: 0000004C31D7E680
First chance exception on 00007FFC39DB3E49 (04242420, CLRDBG_NOTIFICATION_EXCEPTION_CODE)!
Thread DFC created, Entry: coreclr.00007FFC01909290
Thread 1588 created, Entry: coreclr.00007FFC018C4DC0
DLL Loaded: 00007FFC00EE0000 C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.5\System.Private.CoreLib.dll
Breakpoint at 00007FFC00E58BB0 (TLS Callback 1 (clrjit.dll)) set!
DLL Loaded: 00007FFC00D90000 C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.5\clrjit.dll
INT3 breakpoint "TLS Callback 1 (clrjit.dll)" at clrjit.00007FFC00E58BB0 (00007FFC00E58BB0)!
Thread C40 created, Entry: coreclr.00007FFC018BF700
DLL Loaded: 00007FFC37D00000 C:\Windows\System32\kernel.appcore.dll
Thread 1A18 created, Entry: ucrtbase.00007FFC3A341480
DLL Loaded: 000002044C590000 C:\SCT\binaries\SimpleClassicThemeTaskbar.dll
Thread 1A18 exit
DLL Loaded: 00007FFC33EC0000 C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.5\System.Runtime.dll
DLL Loaded: 00007FFC37820000 C:\Windows\System32\uxtheme.dll
DLL Loaded: 00007FFC00D20000 C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.5\System.Linq.dll
DLL Loaded: 00007FFC000B0000 C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\5.0.5\System.Windows.Forms.dll
DLL Loaded: 00007FFC335C0000 C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.5\System.Threading.Thread.dll
DLL Loaded: 00007FFC31C60000 C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\5.0.5\Microsoft.Win32.SystemEvents.dll
EXCEPTION_DEBUG_INFO:
           dwFirstChance: 1
           ExceptionCode: E06D7363 (CPP_EH_EXCEPTION)
          ExceptionFlags: 00000001
        ExceptionAddress: 00007FFC39DB3E49 kernelbase.00007FFC39DB3E49
        NumberParameters: 4
ExceptionInformation[00]: 0000000019930520
ExceptionInformation[01]: 0000004C31D7B3C0
ExceptionInformation[02]: 00007FFC01C7D400 coreclr.00007FFC01C7D400
ExceptionInformation[03]: 00007FFC017E0000 coreclr.00007FFC017E0000
First chance exception on 00007FFC39DB3E49 (E06D7363, CPP_EH_EXCEPTION)!
EXCEPTION_DEBUG_INFO:
           dwFirstChance: 1
           ExceptionCode: E06D7363 (CPP_EH_EXCEPTION)
          ExceptionFlags: 00000001
        ExceptionAddress: 00007FFC39DB3E49 kernelbase.00007FFC39DB3E49
        NumberParameters: 4
ExceptionInformation[00]: 0000000019930520
ExceptionInformation[01]: 0000000000000000
ExceptionInformation[02]: 0000000000000000
ExceptionInformation[03]: 0000000000000000
First chance exception on 00007FFC39DB3E49 (E06D7363, CPP_EH_EXCEPTION)!
```
(The E06D7363 exceptions will just repeat endlessly.)

**Comment by Craftplacer** [comment]
We're self-aware that this error is happening, but there a few things to point out:

1. The builds aren't expected to work outright
2. The method of compiling the program differs when building via Visual Studio (since GitHub Actions is running CLI commands only) and probably require some tweaking until a proper build is being produced

**Comment by BlohoJo** [comment]
For what it's worth, here's the x64dbg from the previous working version (0.0.7744.40762).

Line 88 has:
```
DLL Loaded: 0000021967450000 C:\SCT\Taskbar\SimpleClassicThemeTaskbar.dll
```
...no `C:\SCT\binaries\`... in the path. I feel like that may be where the problem is.

```
Initializing wait objects...
Initializing debugger...
Initializing debugger functions...
Setting JSON memory management functions...
Initializing Zydis...
Getting directory information...
Start file read thread...
Retrieving syscall indices...
Symbol Path: C:\Program Files\x64dbg\x64\symbols
Allocating message stack...
Initializing global script variables...
Registering debugger commands...
Registering GUI command handler...
Registering expression functions...
Registering format functions...
Registering Script DLL command handler...
Starting command loop...
Initialization successful!
Loading plugins...
Handling command line...
  "C:\Program Files\x64dbg\x64\x64dbg.exe" 
Syscall indices loaded!
Error codes database loaded!
Exception codes database loaded!
NTSTATUS codes database loaded!
Windows constant database loaded!
Reading notes file...
File read thread finished!
Debugging: C:\SCT\Taskbar\SimpleClassicThemeTaskbar.exe
Database file: C:\Program Files\x64dbg\x64\db\SimpleClassicThemeTaskbar.exe.dd64
Process Started: 00007FF6F1D50000 C:\SCT\Taskbar\SimpleClassicThemeTaskbar.exe
  "C:\SCT\Taskbar\SimpleClassicThemeTaskbar.exe"
  argv[0]: C:\SCT\Taskbar\SimpleClassicThemeTaskbar.exe
Breakpoint at 00007FF6F1D5FF70 (entry breakpoint) set!
DLL Loaded: 00007FFC3C650000 C:\Windows\System32\ntdll.dll
DLL Loaded: 00007FFC3B330000 C:\Windows\System32\kernel32.dll
DLL Loaded: 00007FFC39D90000 C:\Windows\System32\KernelBase.dll
DLL Loaded: 00007FFC3B7C0000 C:\Windows\System32\user32.dll
DLL Loaded: 00007FFC3A100000 C:\Windows\System32\win32u.dll
DLL Loaded: 00007FFC3B300000 C:\Windows\System32\gdi32.dll
DLL Loaded: 00007FFC3A210000 C:\Windows\System32\gdi32full.dll
DLL Loaded: 00007FFC3A060000 C:\Windows\System32\msvcp_win.dll
DLL Loaded: 00007FFC3A320000 C:\Windows\System32\ucrtbase.dll
Thread E10 created, Entry: ntdll.00007FFC3C6620E0
Thread D9C created, Entry: ntdll.00007FFC3C6620E0
DLL Loaded: 00007FFC3AAD0000 C:\Windows\System32\shell32.dll
Thread 1DA0 created, Entry: ntdll.00007FFC3C6620E0
DLL Loaded: 00007FFC3B660000 C:\Windows\System32\advapi32.dll
DLL Loaded: 00007FFC3A9D0000 C:\Windows\System32\msvcrt.dll
DLL Loaded: 00007FFC3B480000 C:\Windows\System32\sechost.dll
DLL Loaded: 00007FFC3A8A0000 C:\Windows\System32\rpcrt4.dll
System breakpoint reached!
DLL Loaded: 00007FFC3A870000 C:\Windows\System32\imm32.dll
DLL Loaded: 0000000180000000 C:\Program Files\Prio\prio.dll
INT3 breakpoint "entry breakpoint" at <simpleclassicthemetaskbar.EntryPoint> (00007FF6F1D5FF70)!
DLL Loaded: 00007FFC1E400000 C:\Program Files\dotnet\host\fxr\5.0.5\hostfxr.dll
DLL Loaded: 00007FFC1E380000 C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.5\hostpolicy.dll
Breakpoint at 00007FFC1983BBE0 (TLS Callback 1 (coreclr.dll)) set!
Breakpoint at 00007FFC1983C040 (TLS Callback 2 (coreclr.dll)) set!
DLL Loaded: 00007FFC19700000 C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.5\coreclr.dll
DLL Loaded: 00007FFC3BF60000 C:\Windows\System32\ole32.dll
DLL Loaded: 00007FFC3BC00000 C:\Windows\System32\combase.dll
DLL Loaded: 00007FFC3B230000 C:\Windows\System32\oleaut32.dll
INT3 breakpoint "TLS Callback 1 (coreclr.dll)" at coreclr.00007FFC1983BBE0 (00007FFC1983BBE0)!
INT3 breakpoint "TLS Callback 2 (coreclr.dll)" at coreclr.00007FFC1983C040 (00007FFC1983C040)!
DLL Loaded: 00007FFC3A630000 C:\Windows\System32\bcryptprimitives.dll
Thread 680 created, Entry: coreclr.00007FFC197E4ED0
EXCEPTION_DEBUG_INFO:
           dwFirstChance: 1
           ExceptionCode: 04242420 (CLRDBG_NOTIFICATION_EXCEPTION_CODE)
          ExceptionFlags: 00000000
        ExceptionAddress: 00007FFC39DB3E49 kernelbase.00007FFC39DB3E49
        NumberParameters: 3
ExceptionInformation[00]: 0000000031415927
ExceptionInformation[01]: 00007FFC19700000 coreclr.00007FFC19700000
ExceptionInformation[02]: 0000005248F7E4B0
First chance exception on 00007FFC39DB3E49 (04242420, CLRDBG_NOTIFICATION_EXCEPTION_CODE)!
Thread 1AC4 created, Entry: coreclr.00007FFC19829290
Thread 79C created, Entry: coreclr.00007FFC197E4DC0
DLL Loaded: 00007FFC15410000 C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.5\System.Private.CoreLib.dll
Breakpoint at 00007FFC1D758BB0 (TLS Callback 1 (clrjit.dll)) set!
DLL Loaded: 00007FFC1D690000 C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.5\clrjit.dll
INT3 breakpoint "TLS Callback 1 (clrjit.dll)" at clrjit.00007FFC1D758BB0 (00007FFC1D758BB0)!
Thread 153C created, Entry: coreclr.00007FFC197DF700
DLL Loaded: 00007FFC37D00000 C:\Windows\System32\kernel.appcore.dll
Thread D10 created, Entry: ucrtbase.00007FFC3A341480
Thread D10 exit
DLL Loaded: 0000021967450000 C:\SCT\Taskbar\SimpleClassicThemeTaskbar.dll
DLL Unloaded: 0000021967450000 simpleclassicthemetaskbar.dll
DLL Loaded: 0000021967450000 C:\SCT\Taskbar\SimpleClassicThemeTaskbar.dll
DLL Loaded: 00007FFC355C0000 C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.5\System.Runtime.dll
DLL Loaded: 00007FFC37820000 C:\Windows\System32\uxtheme.dll
DLL Loaded: 00007FFC31960000 C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.5\System.Linq.dll
DLL Loaded: 00007FFC147A0000 C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\5.0.5\System.Windows.Forms.dll
DLL Loaded: 00007FFC2A5C0000 C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.5\System.Collections.dll
DLL Loaded: 00007FFC35570000 C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.5\System.ComponentModel.Primitives.dll
DLL Loaded: 00007FFC1D800000 C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\5.0.5\System.Windows.Forms.Primitives.dll
DLL Loaded: 00007FFC34F90000 C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.5\System.Runtime.InteropServices.dll
DLL Loaded: 00007FFC338A0000 C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.5\System.Drawing.Primitives.dll
DLL Loaded: 00007FFC33830000 C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.5\System.Collections.Specialized.dll
DLL Loaded: 00007FFC33FE0000 C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.5\System.Threading.Thread.dll
DLL Loaded: 00007FFC33780000 C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\5.0.5\Microsoft.Win32.SystemEvents.dll
DLL Loaded: 00007FFC269C0000 C:\SCT\Taskbar\SimpleClassicThemeTaskbar.CodeBridge.dll
DLL Loaded: 00007FFC222C0000 C:\Windows\System32\vcruntime140.dll
DLL Loaded: 00007FFC1BCE0000 C:\Windows\System32\msvcp140.dll
DLL Loaded: 00007FFC221B0000 C:\Windows\System32\vcruntime140_1.dll
DLL Loaded: 00007FFC32850000 C:\Windows\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.19041.630_none_fae7a41d761b04f0\GdiPlus.dll
DLL Loaded: 00007FFC37A10000 C:\Windows\System32\dwmapi.dll
DLL Loaded: 00007FFC219E0000 C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.488_none_ca04af081b815d21\comctl32.dll
DLL Loaded: 00007FFC27A40000 C:\Windows\System32\mscoree.dll
DLL Loaded: 00007FFC1F940000 C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscoreei.dll
DLL Loaded: 00007FFC3BBA0000 C:\Windows\System32\shlwapi.dll
DLL Loaded: 00007FFC356F0000 C:\Windows\System32\version.dll
DLL Loaded: 0000021966750000 C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.5\mscorlib.dll
DLL Loaded: 00007FFC33660000 C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.5\System.Collections.NonGeneric.dll
DLL Loaded: 00007FFC20BD0000 C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.5\System.Diagnostics.Process.dll
DLL Loaded: 00007FFC28000000 C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.5\System.IO.FileSystem.dll
DLL Loaded: 00007FFC33EC0000 C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.5\System.Runtime.InteropServices.RuntimeInformation.dll
DLL Loaded: 00007FFC27A00000 C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.5\System.Memory.dll
DLL Loaded: 00007FFC1BA40000 C:\Windows\System32\icu.dll
DLL Loaded: 00007FFC33970000 C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.5\Microsoft.Win32.Primitives.dll
DLL Loaded: 00007FFC32A00000 C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.5\System.Threading.dll
DLL Loaded: 00007FFC2D2F0000 C:\Windows\System32\TextShaping.dll
DLL Loaded: 00007FFC3B540000 C:\Windows\System32\msctf.dll
DLL Loaded: 00007FFC30F90000 C:\Windows\System32\TextInputFramework.dll
DLL Loaded: 00007FFC35950000 C:\Windows\System32\CoreMessaging.dll
DLL Loaded: 00007FFC34200000 C:\Windows\System32\CoreUIComponents.dll
DLL Loaded: 00007FFC3BB20000 C:\Windows\System32\ws2_32.dll
DLL Loaded: 00007FFC38AD0000 C:\Windows\System32\ntmarta.dll
DLL Loaded: 00007FFC35F00000 C:\Windows\System32\WinTypes.dll
DLL Loaded: 00007FFC3C090000 C:\Windows\System32\SHCore.dll
Thread AAC created, Entry: coreclr.00007FFC197D7400
Thread 189C created, Entry: coreclr.00007FFC197DEE90
Thread 189C exit
Thread 1970 created, Entry: ntdll.00007FFC3C6620E0
Thread 229C created, Entry: ntdll.00007FFC3C6620E0
DLL Loaded: 00007FFC320D0000 C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.5\Microsoft.Win32.Registry.dll
Thread C70 created, Entry: combase.00007FFC3BCCA7F0
Thread D18 created, Entry: ntdll.00007FFC3C6620E0
Thread D70 created, Entry: ntdll.00007FFC3C6620E0
Thread E10 exit
Thread D9C exit
Thread 1DA0 exit
Thread 680 exit
Thread D70 exit
Thread C70 exit
Thread 229C exit
Thread 1970 exit
Thread 1AC4 exit
Thread AAC exit
Thread 79C exit
Thread D18 exit
Thread 153C exit
Process stopped with exit code 0x0
Saving database to C:\Program Files\x64dbg\x64\db\SimpleClassicThemeTaskbar.exe.dd64 0ms
Debugging stopped!
```
It exits when it's run directly with a dialog to load it from SCT.exe.

**Comment by Craftplacer** [comment]
A native debugging tool won't help us, this program is running on .NET and itself has already dumped the necessary stack trace for steps for fixing the problem:
```
Application: SimpleClassicThemeTaskbar.exe
CoreCLR Version: 5.0.621.22011
.NET Version: 5.0.6
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException: Could not load file or assembly 'SimpleClassicThemeTaskbar.CodeBridge, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'SimpleClassicThemeTaskbar.CodeBridge, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
   at SimpleClassicThemeTaskbar.ApplicationEntryPoint.Main(String[] args)
```

You don't have to investigate this matter yourself (it is already known to me), because the pure problem is the build script that compiled the program.

**Comment by Craftplacer** [comment]
It seems like that @AEAEAEAE4343 finally fixed the issue with https://github.com/AEAEAEAE4343/SimpleClassicThemeTaskbar/commit/e2d5da025dfd63c064f82cceb91aa41480efa3d4.
