### ISSUE TITLE
Developer version 2021.05.19 still crashes on startup

### ISSUE THREAD

**Issue by BlohoJo** [AEAEAEAE4343/SimpleClassicThemeTaskbar#27]
Different message than previously:

```
Faulting application name: SimpleClassicThemeTaskbar.exe, version: 0.0.7809.19559, time stamp: 0x60513887
Faulting module name: KERNELBASE.dll, version: 10.0.19041.572, time stamp: 0x1183946c
Exception code: 0xe0434352
Fault offset: 0x0000000000023e49
Faulting process id: 0x864
Faulting application start time: 0x01d74dc83a537c0d
Faulting application path: C:\SCT\Taskbar\SimpleClassicThemeTaskbar.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 447bde2b-f519-4b1a-8787-20213e527a1d
Faulting package full name: 
Faulting package-relative application ID: 
```

```
Application: SimpleClassicThemeTaskbar.exe
CoreCLR Version: 5.0.521.16609
.NET Version: 5.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException (0x80040154): Retrieving the COM class factory for component with CLSID {C2F03A33-21F5-47FA-B4BB-156362A2F239} failed due to the following error: 80040154 Class not registered (0x80040154 (REGDB_E_CLASSNOTREG)).
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type)
   at SimpleClassicThemeTaskbar.Helpers.NativeMethods.UnmanagedCodeMigration.InitializeVdmInterface() in D:\a\SimpleClassicThemeTaskbar\SimpleClassicThemeTaskbar\SimpleClassicThemeTaskbar\Helpers\NativeMethods\UnmanagedCodeMigration.cs:line 340
   at SimpleClassicThemeTaskbar.ApplicationEntryPoint.Main(String[] args) in D:\a\SimpleClassicThemeTaskbar\SimpleClassicThemeTaskbar\SimpleClassicThemeTaskbar\ApplicationEntryPoint.cs:line 202
```

**Comment by AEAEAEAE4343** [comment]
Listen, these builds are compiled right after we push something to the repository. This means that new and unfinished code could be pushed and compiled into the dev build. The idea is that the dev builds don’t have to work when we don’t need them to.

**Comment by BlohoJo** [comment]
Sorry about that. :\

I guess I'm not understanding the point of a compiling an exe that does not function. I was under the assumption that it was at the very least not *supposed* to crash, and was working for the people who compiled it.

I assume I should wait for the next alpha or beta to attempt to use the compiled .exe's as a user/tester.

**Comment by Craftplacer** [comment]
> 
> 
> Sorry about that. :\
> 
> I guess I'm not understanding the point of a compiling an exe that does not function. I was under the assumption that it was at the very least not _supposed_ to crash, and was working for the people who compiled it.
> 
> I assume I should wait for the next alpha or beta to attempt to use the compiled .exe's as a user/tester.

It's alright, you can use dev builds for having a sneak peek of what's new, but reporting issues on them as they literally pop up doesn't much because we're the same ones who will see it as well (i.e. we already know of it happening).

It makes much more sense to make bug reports on stable versions, since after all, stable versions aren't expected to fail, unlike the dev builds.
